import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowDownToLine, ArrowRight, Check, FlaskConical, Gauge, Workflow } from "lucide-react";
import { Container } from "@/components/Container";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { Button } from "@/components/Button";
import { TechnicalGraphic } from "@/components/TechnicalGraphic";
import { getProgram, programs } from "@/data/programs";
import { pageMetadata, siteUrl } from "@/lib/seo";

export function generateStaticParams() { return programs.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { return params.then(({ slug }) => { const item = getProgram(slug); return item ? pageMetadata(`${item.name} Chemical Programme`, item.description, `/programs/${item.slug}`) : {}; }); }

export default async function ProgramPage({ params }: { params: Promise<{ slug: string }> }) {
  const program = getProgram((await params).slug); if (!program) notFound();
  const isFibre = program.slug === "fibramax";
  const structuredData = { "@context": "https://schema.org", "@graph": [{ "@type": "Service", name: `${program.name} — ${program.label}`, description: program.description, url: `${siteUrl}/programs/${program.slug}`, serviceType: "Pulp and paper chemical programme", provider: { "@id": `${siteUrl}/#organization` }, areaServed: "IN" }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl }, { "@type": "ListItem", position: 2, name: "Programmes", item: `${siteUrl}/programs` }, { "@type": "ListItem", position: 3, name: program.name, item: `${siteUrl}/programs/${program.slug}` }] }] };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <section className="relative isolate overflow-hidden bg-[#0b2239] py-9 text-white sm:py-12 lg:py-16">
      <div className="grid-fade absolute inset-0 opacity-35" /><div className="absolute -right-10 top-0 h-full w-[57%] overflow-hidden text-[#16943e]/30"><TechnicalGraphic variant={isFibre ? "fibre" : "program"} className="absolute right-[-4rem] top-1/2 w-[45rem] -translate-y-1/2" /></div>
      <Container className="relative"><Breadcrumbs items={[{ label: "Programs", href: "/programs" }, { label: program.name }]} /><div className="mt-12 grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div className="max-w-4xl"><p className="tech-label text-[#b7d7bd]">{program.eyebrow}</p><h1 className="mt-4 text-5xl font-bold tracking-[-.065em] sm:text-6xl lg:text-7xl">{program.name}</h1><p className="mt-3 text-lg font-medium text-[#b7d7bd] sm:text-xl">{program.label}</p><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">{program.description}</p></div><div className="border-l border-white/20 pl-6 lg:mb-1"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#b7d7bd]">Maven signature programme</p><p className="mt-3 max-w-xs text-sm leading-6 text-slate-300">A field-led technical approach shaped around the operating conditions of your process.</p></div></div></Container>
    </section>
    <section className="py-16 sm:py-24 lg:py-28"><Container><div className="grid gap-14 lg:grid-cols-[.78fr_1.22fr]"><aside className="border-t-4 border-[#16943e] bg-[#f3f7fa] p-7 sm:p-9"><p className="eyebrow">The challenge</p><p className="mt-5 text-2xl font-bold leading-9 tracking-[-.045em] text-slate-900 sm:text-3xl sm:leading-10">{program.challenge}</p><Button href="/contact" className="mt-9">Technical enquiry <ArrowRight size={16} /></Button></aside><div><div className="flex items-center gap-3"><Workflow className="text-[#16943e]" size={23} /><p className="eyebrow">Programme approach</p></div><h2 className="mt-5 text-4xl font-bold tracking-[-.06em] text-slate-950">A deliberate process, not a one-size-fits-all chemical.</h2><div className="mt-11 grid gap-7 md:grid-cols-3">{program.approach.map((step, index) => <article key={step} className="process-node relative"><div className="grid h-[4.25rem] w-[4.25rem] place-items-center border border-[#0753b5]/25 bg-white text-xl font-black tracking-[-.05em] text-[#0753b5] shadow-lg shadow-blue-950/5">0{index + 1}</div><p className="mt-6 text-base leading-7 text-slate-700">{step}</p></article>)}</div></div></div></Container></section>
    <section className="relative overflow-hidden bg-[#0753b5] py-16 text-white sm:py-24"><div className="absolute inset-0 paper-lines opacity-30" /><Container className="relative"><div className="grid gap-10 lg:grid-cols-[.6fr_1.4fr]"><div><div className="flex items-center gap-3"><Gauge className="text-[#8be1a5]" size={22} /><p className="eyebrow text-[#8be1a5]">Technical value</p></div><h2 className="mt-5 text-4xl font-bold tracking-[-.06em]">Value that connects across the system.</h2></div><div className="grid gap-px border border-white/20 bg-white/20 md:grid-cols-3">{program.benefits.map((benefit, index) => <div key={benefit} className="bg-[#0753b5]/90 p-6"><span className="text-xs font-black tracking-[.16em] text-[#8be1a5]">0{index + 1}</span><Check className="mt-8 text-[#8be1a5]" size={20} /><p className="mt-5 text-sm font-semibold leading-6 text-white">{benefit}</p></div>)}</div></div></Container></section>
    {program.components && <section className="py-16 sm:py-24"><Container><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Programme components</p><h2 className="mt-4 text-4xl font-bold tracking-[-.06em] text-slate-950">A selectable chemistry framework.</h2><p className="mt-5 max-w-md text-base leading-7 text-slate-600">The final combination is set through laboratory evaluation and system-charge analysis.</p></div><div className="overflow-x-auto border border-slate-200 bg-white shadow-xl shadow-slate-900/[.04]"><table className="min-w-full text-left"><thead className="bg-[#061a37] text-xs uppercase tracking-[.14em] text-white"><tr><th className="p-5">Component</th><th className="p-5">Dosing point</th><th className="p-5">Dosage</th></tr></thead><tbody>{program.components.map((component, index) => <tr key={component.name} className="border-t border-slate-200 transition hover:bg-[#f3f7fa]"><td className="p-5 font-bold text-slate-900"><span className="mr-3 text-[.65rem] text-[#16943e]">0{index + 1}</span>{component.name}</td><td className="p-5 text-slate-600">{component.point}</td><td className="p-5 font-semibold text-slate-700">{component.dosage}</td></tr>)}</tbody></table></div></div></Container></section>}
    {program.applicationMethod && <section className="technical-surface border-y border-slate-200 py-16 sm:py-24"><Container><div className="grid gap-10 lg:grid-cols-2"><div className="bg-white p-7 shadow-xl shadow-blue-950/[.04] sm:p-9"><p className="eyebrow">Application method</p><h2 className="mt-5 text-4xl font-bold tracking-[-.06em] text-slate-950">Prepare with control.</h2><ol className="mt-9 space-y-5">{program.applicationMethod.map((step, index) => <li key={step} className="grid grid-cols-[3rem_1fr] gap-4 border-t border-slate-200 pt-5"><span className="text-xl font-black tracking-[-.05em] text-[#0753b5]">0{index + 1}</span><span className="pt-0.5 text-base leading-7 text-slate-700">{step}</span></li>)}</ol></div>{program.properties && <div className="overflow-hidden border border-slate-200 bg-white"><div className="relative overflow-hidden bg-[#061a37] p-7 text-white"><TechnicalGraphic variant="fibre" className="absolute -right-10 -top-12 h-48 w-80 text-[#16943e]/30" /><div className="relative"><FlaskConical className="text-[#8be1a5]" size={22} /><p className="mt-5 tech-label text-[#8be1a5]">Technical reference</p><h2 className="mt-3 text-2xl font-bold">Typical properties</h2></div></div><dl>{program.properties.map((property, index) => <div key={property.label} className="spec-row grid grid-cols-[1fr_1.1fr] gap-4 border-t border-slate-200 px-6 py-5 text-sm"><dt className="font-semibold text-slate-500"><span className="mr-2 text-[.65rem] font-black text-[#16943e]">0{index + 1}</span>{property.label}</dt><dd className="font-bold leading-6 text-slate-900">{property.value}</dd></div>)}</dl></div>}</div></Container></section>}
    <section className="bg-[#061a37] py-16 text-white sm:py-20"><Container><div className="flex flex-wrap items-end justify-between gap-8"><div><p className="eyebrow text-[#8be1a5]">Technical documentation</p><h2 className="mt-4 text-4xl font-bold tracking-[-.06em]">Continue the evaluation with Maven.</h2></div><a href={program.resource} className="inline-flex min-h-11 items-center gap-2 bg-white px-5 text-sm font-bold text-[#0753b5] transition hover:bg-[#eaf3ff]"><ArrowDownToLine size={17} />Download programme information</a></div></Container></section>
  </>;
}
