import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowRight, Check, FileText, PackageCheck, Settings2 } from "lucide-react";
import { Container } from "@/components/Container";
import { Button } from "@/components/Button";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { ProductCard } from "@/components/ProductCard";
import { TechnicalGraphic, productGraphicVariant } from "@/components/TechnicalGraphic";
import { getProduct, products } from "@/data/products";
import { pageMetadata, siteUrl } from "@/lib/seo";

export function generateStaticParams() { return products.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { return params.then(({ slug }) => { const product = getProduct(slug); return product ? pageMetadata(`${product.name} Paper Chemical`, product.shortDescription, `/products/${product.slug}`) : {}; }); }

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const product = getProduct((await params).slug); if (!product) notFound();
  const related = products.filter((item) => product.relatedProducts.includes(item.slug));
  const graphic = productGraphicVariant(product);
  const structuredData = { "@context": "https://schema.org", "@graph": [{ "@type": "Product", name: product.name, description: product.description, sku: product.code, category: product.category, url: `${siteUrl}/products/${product.slug}`, brand: { "@type": "Brand", name: "Maven Solutions" }, manufacturer: { "@id": `${siteUrl}/#organization` }, additionalProperty: product.properties.map((property) => ({ "@type": "PropertyValue", name: property.label, value: property.value })) }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: siteUrl }, { "@type": "ListItem", position: 2, name: "Products", item: `${siteUrl}/products` }, { "@type": "ListItem", position: 3, name: product.name, item: `${siteUrl}/products/${product.slug}` }] }] };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <section className="relative isolate overflow-hidden bg-[#0b2239] py-8 text-white sm:py-10 lg:py-12">
      <div className="grid-fade absolute inset-0 opacity-35" />
      <div className="absolute -right-10 top-0 h-full w-[50%] overflow-hidden text-[#16943e]/30"><TechnicalGraphic variant={graphic} className="absolute right-[-4rem] top-1/2 w-[38rem] -translate-y-1/2" /></div>
      <Container className="relative"><Breadcrumbs items={[{ label: "Products", href: "/products" }, { label: product.name }]} /><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div className="max-w-4xl"><p className="tech-label text-[#b7d7bd]">{product.category}</p><div className="mt-4 flex flex-wrap items-baseline gap-x-6 gap-y-2"><h1 className="text-5xl font-bold tracking-[-.06em] sm:text-6xl">{product.name}</h1><span className="border border-white/20 bg-white/5 px-3 py-1.5 text-sm font-bold tracking-[.06em] text-[#b7d7bd]">{product.code}</span></div><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-200">{product.shortDescription}</p></div><Button href="/contact" variant="light">Request technical information <ArrowRight size={16} /></Button></div></Container>
    </section>
    <section className="py-16 sm:py-24 lg:py-28"><Container><div className="grid gap-14 xl:grid-cols-[minmax(0,1.15fr)_minmax(25rem,.85fr)] xl:gap-20"><div><p className="eyebrow">Product overview</p><p className="mt-6 max-w-3xl text-xl leading-9 text-slate-700 sm:text-2xl sm:leading-10">{product.description}</p><div className="mt-14 grid gap-4 sm:grid-cols-3">{product.benefits.map((benefit, index) => <article key={benefit} className="border-t-2 border-[#16943e] bg-[#f3f7fa] p-5"><span className="text-xs font-black tracking-[.15em] text-[#0753b5]">0{index + 1}</span><Check className="mt-7 text-[#16943e]" size={19} /><p className="mt-4 text-sm font-semibold leading-6 text-slate-800">{benefit}</p></article>)}</div></div><aside className="h-fit overflow-hidden border border-slate-200 bg-white shadow-xl shadow-slate-900/[.04]"><div className="relative overflow-hidden bg-[#0753b5] p-7 text-white"><TechnicalGraphic variant={graphic} className="absolute -right-20 -top-10 h-52 w-80 text-white/20" /><div className="relative"><p className="tech-label text-[#aeecc0]">Technical reference</p><h2 className="mt-3 text-2xl font-bold tracking-[-.04em]">Typical properties</h2></div></div><dl>{product.properties.map((property, index) => <div key={property.label} className="spec-row grid grid-cols-[minmax(8rem,.8fr)_1.2fr] gap-5 border-b border-slate-200 px-6 py-5 text-sm last:border-0"><dt className="font-semibold text-slate-500"><span className="mr-2 text-[.65rem] font-black text-[#16943e]">0{index + 1}</span>{property.label}</dt><dd className="font-bold leading-6 text-slate-900">{property.value}</dd></div>)}</dl><div className="border-t border-slate-200 bg-[#f8fafb] p-5"><p className="flex gap-2 text-xs leading-5 text-slate-500"><FileText size={15} className="shrink-0" />Source: {product.source}</p></div></aside></div></Container></section>
    <section className="technical-surface border-y border-slate-200 py-16 sm:py-24"><Container><div className="grid gap-12 lg:grid-cols-2"><div><div className="flex items-center gap-3"><Settings2 className="text-[#16943e]" size={22} /><p className="eyebrow">Application pathway</p></div><h2 className="mt-5 text-4xl font-bold tracking-[-.06em] text-slate-950">Built for the process point that matters.</h2><div className="mt-8 grid gap-3">{product.applications.map((application, index) => <div key={application} className="flex items-center gap-5 border border-slate-200 bg-white p-5"><span className="grid h-9 w-9 shrink-0 place-items-center bg-[#061a37] text-xs font-black text-[#aeecc0]">0{index + 1}</span><p className="text-base font-semibold text-slate-800">{application}</p></div>)}</div></div>{product.handling && <div className="fiber-surface border border-slate-200 p-7 sm:p-9"><div className="flex items-center gap-3"><PackageCheck className="text-[#0753b5]" size={22} /><p className="eyebrow">Handling & packaging</p></div><h2 className="mt-5 text-3xl font-bold tracking-[-.055em] text-slate-950">Practical reference for the site team.</h2><ul className="mt-8 space-y-4">{product.handling.map((item) => <li key={item} className="flex gap-4 border-t border-slate-300/80 pt-4 text-base leading-7 text-slate-700"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-[#16943e]" />{item}</li>)}</ul></div>}</div></Container></section>
    {related.length > 0 && <section className="py-16 sm:py-24"><Container><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Continue exploring</p><h2 className="mt-3 text-4xl font-bold tracking-[-.06em] text-slate-950">Related technical products</h2></div><Button href="/products" variant="secondary">View catalogue <ArrowRight size={16} /></Button></div><div className="mt-10 grid gap-4 md:grid-cols-3">{related.map((item) => <ProductCard key={item.slug} product={item} />)}</div></Container></section>}
  </>;
}
