import { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Droplets, Network, Paperclip, ScanLine } from "lucide-react";
import { Container } from "@/components/Container";
import { products } from "@/data/products";
import { pageMetadata } from "@/lib/seo";
export const metadata: Metadata = pageMetadata("Paper Mill Chemical Solutions", "Explore pulp and paper chemical solutions for retention, drainage, filler efficiency, process water, recovery, sizing and starch.", "/solutions");
const sections = [{ id: "retention", title: "Improve retention & drainage", copy: "Build a more controllable wet end with retention aids and programme-led optimisation.", icon: Network, categories: ["Retention & Drainage"] }, { id: "filler", title: "Increase filler efficiency", copy: "Explore the FIBRAMAX programme for controlled filler fixation within the fibre network.", icon: Paperclip, program: "/programs/fibramax" }, { id: "water", title: "Manage process water & recovery", copy: "Control particulate load, improve water clarity and support downstream fibre recovery.", icon: Droplets, categories: ["Process Water & Fines Control", "Fibre Recovery & ETP"] }, { id: "sizing", title: "Optimise surface sizing & starch", copy: "Support surface properties, strength contribution and starch-use efficiency at the size press.", icon: ScanLine, categories: ["Surface Sizing & Starch"] }];
export default function Solutions() { return <><section className="bg-[#f4f8fc] py-20 sm:py-28"><Container><p className="eyebrow">Solutions</p><h1 className="mt-3 max-w-4xl text-5xl font-bold tracking-[-.07em] text-slate-950 sm:text-6xl">Find chemistry by the problem you need to solve.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Maven’s products and programs are organised around paper-machine requirements, rather than product codes alone.</p></Container></section><div className="py-8"><Container><div className="flex flex-wrap gap-x-6 gap-y-3">{sections.map((section) => <a key={section.id} className="text-sm font-bold text-[#0753b5] transition hover:text-[#16943e]" href={`#${section.id}`}>{section.title}</a>)}</div></Container></div>{sections.map((section, index) => { const Icon = section.icon; const items = section.categories ? products.filter((product) => section.categories?.includes(product.category)) : []; return <section key={section.id} id={section.id} className={index % 2 ? "bg-[#f8fbfd] py-20 sm:py-28" : "py-20 sm:py-28"}><Container><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><Icon className="text-[#16943e]" size={32} /><h2 className="mt-6 text-4xl font-bold tracking-[-.06em] text-slate-950">{section.title}</h2><p className="mt-5 text-base leading-7 text-slate-600">{section.copy}</p>{section.program && <Link href={section.program} className="mt-7 inline-flex items-center gap-2 border-b border-[#0753b5] pb-1 text-sm font-bold text-[#0753b5] transition hover:translate-x-0.5 hover:text-[#16943e]">Explore FIBRAMAX <ArrowRight size={16} /></Link>}</div>{items.length > 0 && <div className="grid gap-3 sm:grid-cols-2">{items.map((product) => <Link key={product.slug} href={`/products/${product.slug}`} className="rounded-md border border-slate-200 bg-white p-5 shadow-sm transition duration-300 ease-out hover:-translate-y-1 hover:border-[#1769aa] hover:shadow-md"><p className="tech-label">{product.code}</p><h3 className="mt-5 text-xl font-bold">{product.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{product.shortDescription}</p></Link>)}</div>}</div></Container></section>; })}</>; }
