import { Metadata } from "next";
import { ArrowDownToLine, FileText, Files, FlaskConical } from "lucide-react";
import { Container } from "@/components/Container";
export const metadata: Metadata = { title: "Technical Resources" };
const resources = [
  { title: "Maven Solutions Technical Data Sheets", type: "Product technical data", copy: "Nine technical product profiles covering process water, retention, ETP, sizing and starch applications.", href: "/resources/maven-technical-data-sheets.pdf", mark: "01" },
  { title: "REDRAMAX Program", type: "Programme information", copy: "Advance retention and drainage programme information, including programme components and evaluation approach.", href: "/resources/redramax-program.pdf", mark: "02" },
  { title: "FIBRAMAX Program", type: "Programme information", copy: "Advance filler retention programme information, application method and typical properties.", href: "/resources/fibramax-program.pdf", mark: "03" },
  { title: "Maven Solutions Company Profile", type: "Company information", copy: "An overview of Maven’s positioning, offerings, values and contact information.", href: "/resources/maven-solutions-company-profile.pdf", mark: "04" }
];
export default function Resources() { return <><section className="border-b border-[#d8e0e5] bg-[#eef3f5] py-16 sm:py-20"><Container><p className="eyebrow">Technical resources</p><h1 className="mt-4 max-w-4xl text-5xl font-bold tracking-[-.06em] text-[#17212b] sm:text-6xl">Reference material for considered technical evaluation.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#53616e]">Access Maven’s product sheets, programme literature and company information. Consult the technical team for suitability under your process conditions.</p></Container></section><section className="py-16 sm:py-24"><Container><div className="grid gap-8 lg:grid-cols-[.72fr_1.28fr]"><aside className="technical-surface rounded-lg border border-[#d8e0e5] p-7 shadow-sm sm:p-9"><Files className="text-[#287d78]" size={28} /><p className="eyebrow mt-10">Technical library</p><h2 className="mt-5 text-4xl font-bold tracking-[-.06em] text-[#17212b]">Prepared for plant-side conversations.</h2><p className="mt-6 text-base leading-7 text-[#53616e]">Use these resources as a starting point. Maven’s own reference material advises testing against the specific conditions of your process.</p><div className="mt-10 border-t border-[#d8e0e5] pt-5 text-sm font-semibold text-[#17212b]">4 available documents<br /><span className="mt-1 block text-xs font-normal text-[#53616e]">Product data, programme information and company profile</span></div></aside><div className="grid gap-4 sm:grid-cols-2">{resources.map((resource) => <article key={resource.title} className="group relative flex min-h-[290px] flex-col rounded-lg border border-[#d8e0e5] bg-white p-7 shadow-sm transition duration-300 ease-out hover:-translate-y-1 hover:border-[#1769aa] hover:shadow-md"><FileText className="text-[#287d78]" size={25} /><p className="tech-label mt-9">{resource.type}</p><h2 className="mt-4 text-2xl font-bold tracking-[-.045em] text-[#17212b]">{resource.title}</h2><p className="mt-4 text-sm leading-6 text-[#53616e]">{resource.copy}</p><a className="mt-auto inline-flex min-h-11 items-center gap-2 pt-6 text-sm font-bold text-[#1769aa] transition group-hover:translate-x-0.5 group-hover:text-[#287d78]" href={resource.href}><ArrowDownToLine size={17} />Download PDF</a></article>)}</div></div><div className="mt-10 flex gap-3 rounded-md border-l-2 border-[#287d78] bg-[#eef3f5] px-5 py-4 text-sm leading-6 text-[#53616e]"><FlaskConical className="mt-0.5 shrink-0 text-[#1769aa]" size={18} />The supplied documents state that technical values and specifications are indicative and affected by water quality and process conditions. Customers should perform their own tests before making use decisions.</div></Container></section></>; }
